model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoEncoder
  params:
    monitor: "val/rec_loss"
    freeze_modules: 2
    checkpoint_path: "models/ldm/lsun_beds256/autoencoder.ckpt"
    embed_dim: 3
    n_embed: 8192
    lossconfig:
      target: torch.nn.MSELoss
      
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    wrap: True
    train:
      target: ldm.data.lsun.LSUNBedroomsTrainJSCC
      params:
        txt_file: ''
        data_root: ''
        size: 256
    validation:
      target: ldm.data.lsun.LSUNBedroomsValidationJSCC
      params:
        size: 256
        txt_file: ''
        data_root: ''

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
